apiVersion: v1 
kind: Service
metadata:
  name: rate-my-yoga-teacher-kubernetes
  namespace: default
  labels:
    app: rate-my-yoga-teacher-kubernetes
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  selector:
    app: rate-my-yoga-teacher-kubernetes